import {Search,ArrowRight} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {PostCard} from '@/components/site-parts';
import {posts,topics} from '@/lib/content';
export function ArticleLibrary({topic,query}:{topic:string;query:string}){
const active=topics.includes(topic)?topic:'All entries';
const filtered=posts.filter(p=>(active==='All entries'||p.categories.includes(active))&&(p.title+' '+p.summary+' '+p.categories.join(' ')).toLowerCase().includes(query.trim().toLowerCase()));
function filterUrl(name:string){const params=new URLSearchParams();if(name!=='All entries')params.set('topic',name);if(query)params.set('q',query);return '/blog'+(params.size?'?'+params.toString():'');}
return <><div className="library-toolbar"><nav className="filter-list" aria-label="Filter entries by topic">{['All entries',...topics].map(name=><a className={'filter-button'+(active===name?' selected':'')} href={filterUrl(name)} key={name} aria-current={active===name?'page':undefined}>{name}<span>{name==='All entries'?posts.length:posts.filter(p=>p.categories.includes(name)).length}</span></a>)}</nav><form action="/blog" method="get" className="search-field">{active!=='All entries'&&<input type="hidden" name="topic" value={active}/>}<Search size={17}/><Input aria-label="Search the log" placeholder="Search the log…" type="search" name="q" defaultValue={query}/><Button type="submit" variant="ghost" aria-label="Submit search"><ArrowRight size={18}/></Button></form></div><div className="library-layout"><section aria-label="Log entries"><div className="results-label">{filtered.length} {filtered.length===1?'entry':'entries'}{active!=='All entries'?' / '+active:''}</div>{filtered.length?<div className="post-grid library-grid">{filtered.map(post=><PostCard key={post.id} post={post}/>)}</div>:<div className="empty-state"><Search size={28}/><h2>No entries found.</h2><p>Try another search or explore a different topic.</p><a className="button primary" href="/blog">Clear filters</a></div>}</section><aside className="library-aside"><span className="eyebrow">Behind the log</span><img src="/assets/jewelry.jpg" alt="Jewelry Kenepa" width="72" height="72"/><h2>Hi, I’m Jewelry.</h2><p>Technical consultant. Curious builder. Sharing notes from the Microsoft modern workplace.</p><a className="text-link" href="/about">Meet the author <ArrowRight size={16}/></a><div className="aside-divider"/><span className="eyebrow">A working notebook</span><p>Real problems.<br/>Useful experiments.<br/>Lessons from the field.</p></aside></div></>;}